# Generated by Django 4.2.7 on 2023-11-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('default_address', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('account_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('account_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('when_opened', models.DateTimeField()),
                ('materials_delivered', models.BooleanField()),
                ('last_card_date', models.DateTimeField()),
                ('accepted_applications', models.IntegerField()),
                ('given_cards', models.IntegerField()),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('distance', models.FloatField(default=0)),
                ('status', models.CharField(default='Не начат', max_length=200)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('grade_required', models.IntegerField()),
                ('time_required', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Не назначена', max_length=200)),
                ('comment', models.CharField(default='', max_length=200)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.office')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.route')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasktype')),
            ],
        ),
    ]
