# Generated by Django 4.2.7 on 2023-11-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='condition_1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktype',
            name='condition_2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
