# Generated by Django 4.2.7 on 2023-11-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasktype_condition_1_tasktype_condition_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='coordinate_x',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='coordinate_y',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
