# Generated by Django 4.2.7 on 2023-11-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_employee_default_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='last_card_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='materials_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='office',
            name='when_opened',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
